-- Oracle 19c: 기존 T_USER가 있는 스키마에 한 번 적용하는 첨삭 전용 DDL.
-- 기존 schema.sql 및 모의면접 테이블과 별도로 관리한다.

CREATE SEQUENCE SEQ_T_DOCUMENT_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_DOCUMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_STRENGTH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_IMPROVEMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_CONSISTENCY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE T_DOCUMENT_REVIEW (
    REVIEW_NUM          NUMBER(18) DEFAULT SEQ_T_DOCUMENT_REVIEW.NEXTVAL PRIMARY KEY,
    USER_NUM            NUMBER(9) NOT NULL,
    REVIEW_TITLE        VARCHAR2(200 CHAR) NOT NULL,
    REVIEW_STATUS       VARCHAR2(20 CHAR) DEFAULT 'PROCESSING' NOT NULL,
    REVIEW_MODE         VARCHAR2(20 CHAR) DEFAULT 'comprehensive' NOT NULL,
    CUSTOM_CRITERIA     VARCHAR2(200 CHAR),
    INSTRUCTIONS        VARCHAR2(200 CHAR),
    OVERALL_SUMMARY     CLOB,
    CAREER_PREPARATION_JSON CLOB,
    MODEL_NAME          VARCHAR2(100 CHAR),
    PROMPT_VERSION      VARCHAR2(50 CHAR),
    RESPONSE_VERSION    NUMBER(4) DEFAULT 1 NOT NULL,
    ERROR_MESSAGE       VARCHAR2(1000 CHAR),
    CREATED_AT          TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    FINISHED_AT         TIMESTAMP(6),
    CONSTRAINT FK_REVIEW_USER FOREIGN KEY (USER_NUM)
        REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    CONSTRAINT CK_REVIEW_MODE CHECK (
        REVIEW_MODE IN ('comprehensive', 'expression', 'consistency', 'jobFit', 'evidence', 'custom')
    ),
    CONSTRAINT CK_REVIEW_CUSTOM CHECK (
        (REVIEW_MODE = 'custom' AND CUSTOM_CRITERIA IS NOT NULL
            AND REGEXP_LIKE(CUSTOM_CRITERIA, '[^[:space:]]'))
        OR (REVIEW_MODE <> 'custom' AND CUSTOM_CRITERIA IS NULL)
    ),
    CONSTRAINT CK_REVIEW_VERSION CHECK (RESPONSE_VERSION > 0),
    CONSTRAINT CK_REVIEW_PREPARATION_JSON CHECK (CAREER_PREPARATION_JSON IS JSON STRICT),
    CONSTRAINT CK_REVIEW_STATE CHECK (
        (REVIEW_STATUS = 'PROCESSING' AND FINISHED_AT IS NULL AND ERROR_MESSAGE IS NULL)
        OR (REVIEW_STATUS = 'COMPLETED' AND FINISHED_AT IS NOT NULL AND ERROR_MESSAGE IS NULL)
        OR (REVIEW_STATUS = 'FAILED' AND FINISHED_AT IS NOT NULL AND ERROR_MESSAGE IS NOT NULL)
    ),
    CONSTRAINT CK_REVIEW_TIME CHECK (FINISHED_AT >= CREATED_AT)
);

CREATE INDEX IDX_REVIEW_USER_DATE
    ON T_DOCUMENT_REVIEW(USER_NUM, CREATED_AT DESC, REVIEW_NUM DESC);

CREATE TABLE T_REVIEW_DOCUMENT (
    REVIEW_DOCUMENT_NUM NUMBER(18) DEFAULT SEQ_T_REVIEW_DOCUMENT.NEXTVAL PRIMARY KEY,
    REVIEW_NUM          NUMBER(18) NOT NULL,
    DOCUMENT_TYPE       VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_DOCUMENT_NUM NUMBER(18) NOT NULL,
    DOCUMENT_TITLE      VARCHAR2(200 CHAR) NOT NULL,
    SOURCE_UPDATED_AT   DATE,
    SOURCE_SNAPSHOT_JSON CLOB NOT NULL,
    ORIGINAL_FILE_NAME  VARCHAR2(255 CHAR),
    PDF_SNAPSHOT        BLOB,
    DOCUMENT_SUMMARY    CLOB,
    CONSTRAINT FK_REVIEW_DOC_REVIEW FOREIGN KEY (REVIEW_NUM)
        REFERENCES T_DOCUMENT_REVIEW(REVIEW_NUM) ON DELETE CASCADE,
    CONSTRAINT UQ_REVIEW_DOC_TYPE UNIQUE (REVIEW_NUM, DOCUMENT_TYPE),
    CONSTRAINT UQ_REVIEW_DOC_PAIR UNIQUE (REVIEW_NUM, REVIEW_DOCUMENT_NUM),
    CONSTRAINT CK_REVIEW_DOC_TYPE CHECK (
        DOCUMENT_TYPE IN ('resume', 'cover-letter', 'portfolio')
    ),
    CONSTRAINT CK_REVIEW_DOC_SOURCE CHECK (SOURCE_DOCUMENT_NUM > 0),
    CONSTRAINT CK_REVIEW_DOC_JSON CHECK (SOURCE_SNAPSHOT_JSON IS JSON STRICT)
);

CREATE TABLE T_REVIEW_STRENGTH (
    STRENGTH_NUM        NUMBER(18) DEFAULT SEQ_T_REVIEW_STRENGTH.NEXTVAL PRIMARY KEY,
    REVIEW_NUM          NUMBER(18) NOT NULL,
    REVIEW_DOCUMENT_NUM NUMBER(18),
    DISPLAY_ORDER       NUMBER(9) NOT NULL,
    STRENGTH_CONTENT    CLOB NOT NULL,
    CONSTRAINT FK_REVIEW_STR_REVIEW FOREIGN KEY (REVIEW_NUM)
        REFERENCES T_DOCUMENT_REVIEW(REVIEW_NUM) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_STR_DOC FOREIGN KEY (REVIEW_NUM, REVIEW_DOCUMENT_NUM)
        REFERENCES T_REVIEW_DOCUMENT(REVIEW_NUM, REVIEW_DOCUMENT_NUM) ON DELETE CASCADE,
    CONSTRAINT CK_REVIEW_STR_ORDER CHECK (DISPLAY_ORDER > 0)
);

-- 문서 번호 NULL은 서류 전체 강점이며, 문서별로 배열 순서를 보존한다.
CREATE UNIQUE INDEX UQ_REVIEW_STR_ORDER
    ON T_REVIEW_STRENGTH(REVIEW_NUM, NVL(REVIEW_DOCUMENT_NUM, 0), DISPLAY_ORDER);
CREATE INDEX IDX_REVIEW_STR_DOC
    ON T_REVIEW_STRENGTH(REVIEW_NUM, REVIEW_DOCUMENT_NUM);

CREATE TABLE T_REVIEW_IMPROVEMENT (
    IMPROVEMENT_NUM     NUMBER(18) DEFAULT SEQ_T_REVIEW_IMPROVEMENT.NEXTVAL PRIMARY KEY,
    REVIEW_DOCUMENT_NUM NUMBER(18) NOT NULL,
    DISPLAY_ORDER       NUMBER(9) NOT NULL,
    SECTION_NAME        VARCHAR2(500 CHAR) NOT NULL,
    IMPROVEMENT_TITLE   VARCHAR2(500 CHAR) NOT NULL,
    ISSUE_CONTENT       CLOB NOT NULL,
    ORIGINAL_CONTENT    CLOB NOT NULL,
    SUGGESTED_CONTENT   CLOB NOT NULL,
    REASON_CONTENT      CLOB NOT NULL,
    CONSTRAINT FK_REVIEW_IMP_DOC FOREIGN KEY (REVIEW_DOCUMENT_NUM)
        REFERENCES T_REVIEW_DOCUMENT(REVIEW_DOCUMENT_NUM) ON DELETE CASCADE,
    CONSTRAINT UQ_REVIEW_IMP_ORDER UNIQUE (REVIEW_DOCUMENT_NUM, DISPLAY_ORDER),
    CONSTRAINT CK_REVIEW_IMP_ORDER CHECK (DISPLAY_ORDER > 0)
);

CREATE TABLE T_REVIEW_CONSISTENCY (
    CONSISTENCY_NUM     NUMBER(18) DEFAULT SEQ_T_REVIEW_CONSISTENCY.NEXTVAL PRIMARY KEY,
    REVIEW_NUM          NUMBER(18) NOT NULL,
    DISPLAY_ORDER       NUMBER(9) NOT NULL,
    ISSUE_TYPE          VARCHAR2(30 CHAR) NOT NULL,
    ISSUE_TITLE         VARCHAR2(500 CHAR) NOT NULL,
    RECOMMENDATION      CLOB NOT NULL,
    CONSTRAINT FK_REVIEW_CON_REVIEW FOREIGN KEY (REVIEW_NUM)
        REFERENCES T_DOCUMENT_REVIEW(REVIEW_NUM) ON DELETE CASCADE,
    CONSTRAINT UQ_REVIEW_CON_PAIR UNIQUE (REVIEW_NUM, CONSISTENCY_NUM),
    CONSTRAINT UQ_REVIEW_CON_ORDER UNIQUE (REVIEW_NUM, DISPLAY_ORDER),
    CONSTRAINT CK_REVIEW_CON_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_REVIEW_CON_TYPE CHECK (
        ISSUE_TYPE IN ('mismatch', 'missingEvidence', 'needsConfirmation')
    )
);

CREATE TABLE T_REVIEW_SOURCE (
    CONSISTENCY_NUM     NUMBER(18) NOT NULL,
    DISPLAY_ORDER       NUMBER(9) NOT NULL,
    REVIEW_NUM          NUMBER(18) NOT NULL,
    REVIEW_DOCUMENT_NUM NUMBER(18) NOT NULL,
    SECTION_NAME        VARCHAR2(500 CHAR) NOT NULL,
    SOURCE_CONTENT      CLOB NOT NULL,
    PAGE_NUMBER         NUMBER(6),
    CONSTRAINT PK_REVIEW_SOURCE PRIMARY KEY (CONSISTENCY_NUM, DISPLAY_ORDER),
    CONSTRAINT FK_REVIEW_SRC_ISSUE FOREIGN KEY (REVIEW_NUM, CONSISTENCY_NUM)
        REFERENCES T_REVIEW_CONSISTENCY(REVIEW_NUM, CONSISTENCY_NUM) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_SRC_DOC FOREIGN KEY (REVIEW_NUM, REVIEW_DOCUMENT_NUM)
        REFERENCES T_REVIEW_DOCUMENT(REVIEW_NUM, REVIEW_DOCUMENT_NUM) ON DELETE CASCADE,
    CONSTRAINT CK_REVIEW_SRC_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_REVIEW_SRC_PAGE CHECK (PAGE_NUMBER > 0)
);

CREATE INDEX IDX_REVIEW_SRC_ISSUE ON T_REVIEW_SOURCE(REVIEW_NUM, CONSISTENCY_NUM);
CREATE INDEX IDX_REVIEW_SRC_DOC ON T_REVIEW_SOURCE(REVIEW_NUM, REVIEW_DOCUMENT_NUM);

COMMENT ON TABLE T_DOCUMENT_REVIEW IS '사용자별 통합 첨삭 요청과 종합 결과';
COMMENT ON TABLE T_REVIEW_DOCUMENT IS '첨삭 당시 문서 스냅샷과 문서별 종합 피드백';
COMMENT ON TABLE T_REVIEW_STRENGTH IS '서류 전체 및 문서별 강점';
COMMENT ON TABLE T_REVIEW_IMPROVEMENT IS '문서별 원문과 수정 제안 및 이유';
COMMENT ON TABLE T_REVIEW_CONSISTENCY IS '서류 간 일관성 검토 항목';
COMMENT ON TABLE T_REVIEW_SOURCE IS '일관성 검토 항목별 비교 근거';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.REVIEW_MODE IS '전체 종합 또는 중심 첨삭 기준 1개; comprehensive, expression, consistency, jobFit, evidence, custom';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.CUSTOM_CRITERIA IS '직접 입력 기준; custom일 때 필수이며 최대 200자, 다른 기준에서는 NULL';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.INSTRUCTIONS IS '선택 입력인 추가 요청; 최대 200자';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.MODEL_NAME IS '생성 모델; gpt-6-sol 또는 기존 더미 기록의 dummy-document-review-v2';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.CAREER_PREPARATION_JSON IS '당시 이력서의 지원 직군·직무와 별도 취업 준비 추천 결과 JSON';
COMMENT ON COLUMN T_REVIEW_DOCUMENT.SOURCE_DOCUMENT_NUM IS '원본 문서 번호의 기록용 복사본; 원본 삭제와 독립적으로 보존';
COMMENT ON COLUMN T_REVIEW_DOCUMENT.SOURCE_SNAPSHOT_JSON IS '요청 당시 선택한 실제 문서 내용과 메타데이터 보관본';
COMMENT ON COLUMN T_REVIEW_DOCUMENT.PDF_SNAPSHOT IS '포트폴리오 원본 PDF를 다시 제공할 경우 사용하는 보관본';
COMMENT ON COLUMN T_REVIEW_STRENGTH.REVIEW_DOCUMENT_NUM IS 'NULL이면 서류 전체 강점, 값이 있으면 해당 문서의 강점';
