-- 기존 첨삭 테이블에 적용한다. 과거 기록은 요청 ID 없이 유지한다.
DECLARE
    existing_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO existing_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_DOCUMENT_REVIEW' AND COLUMN_NAME = 'REQUEST_ID';
    IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_DOCUMENT_REVIEW ADD REQUEST_ID VARCHAR2(36 CHAR)';
    END IF;

    SELECT COUNT(*) INTO existing_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_DOCUMENT_REVIEW' AND COLUMN_NAME = 'REQUEST_HASH';
    IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_DOCUMENT_REVIEW ADD REQUEST_HASH VARCHAR2(64 CHAR)';
    END IF;

    SELECT COUNT(*) INTO existing_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'T_DOCUMENT_REVIEW' AND CONSTRAINT_NAME = 'CK_REVIEW_REQUEST';
    IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_DOCUMENT_REVIEW ADD CONSTRAINT CK_REVIEW_REQUEST CHECK (
            (REQUEST_ID IS NULL AND REQUEST_HASH IS NULL)
            OR (REQUEST_ID IS NOT NULL AND REQUEST_HASH IS NOT NULL))';
    END IF;

    SELECT COUNT(*) INTO existing_count FROM USER_INDEXES
    WHERE INDEX_NAME = 'UQ_REVIEW_USER_REQUEST';
    IF existing_count = 0 THEN
        -- 두 인덱스 값이 모두 NULL인 과거 기록은 고유 인덱스에 포함되지 않는다.
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_REVIEW_USER_REQUEST ON T_DOCUMENT_REVIEW(
            CASE WHEN REQUEST_ID IS NOT NULL THEN USER_NUM END, REQUEST_ID)';
    END IF;
END;
/
