-- 기존 첨삭 테이블에 추천 결과 보관 컬럼만 추가한다. 반복 실행 가능하다.
DECLARE
    COLUMN_COUNT NUMBER;
    CONSTRAINT_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO COLUMN_COUNT FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_DOCUMENT_REVIEW' AND COLUMN_NAME = 'CAREER_PREPARATION_JSON';
    IF COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_DOCUMENT_REVIEW ADD (CAREER_PREPARATION_JSON CLOB)';
    END IF;
    SELECT COUNT(*) INTO CONSTRAINT_COUNT FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'T_DOCUMENT_REVIEW' AND CONSTRAINT_NAME = 'CK_REVIEW_PREPARATION_JSON';
    IF CONSTRAINT_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_DOCUMENT_REVIEW ADD CONSTRAINT CK_REVIEW_PREPARATION_JSON CHECK (CAREER_PREPARATION_JSON IS JSON STRICT)';
    END IF;
END;
/
COMMENT ON COLUMN T_DOCUMENT_REVIEW.CAREER_PREPARATION_JSON IS '당시 이력서의 지원 직군·직무와 별도 취업 준비 추천 결과 JSON';
