-- 기존 Oracle DB에 Refresh Token 저장소를 추가합니다.
CREATE TABLE T_REFRESH_TOKEN (
    TOKEN_ID             VARCHAR2(36)        PRIMARY KEY,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    EXPIRES_AT           TIMESTAMP           NOT NULL
);

CREATE INDEX IDX_REFRESH_TOKEN_EXPIRES_AT ON T_REFRESH_TOKEN(EXPIRES_AT);
