-- Oracle 19c: 기존 DB에서 한 번 실행하는 이관 스크립트.
-- 신규 DB는 schema.sql을 사용하고 이 스크립트는 실행하지 않는다.
-- 회원/이력서 쓰기를 중단한 상태에서 실행한 뒤 새 애플리케이션을 배포한다.
-- SQL*Plus / SQLcl에서 실행. 회원의 코드 컬럼은 복사 후에도 유지한다.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- 이력서가 없는 회원, 직군/직무가 서로 다른 기존 값도 원본 그대로 보존한다.
CREATE TABLE T_USER_JOB_CODE_BACKUP AS
SELECT USER_NUM, OCCUPATION_CODE, JOB_CODE, SYSDATE AS BACKED_UP_AT
FROM T_USER;

ALTER TABLE T_RESUME ADD (
    OCCUPATION_CODE VARCHAR2(20) REFERENCES T_OCCUPATION(OCCUPATION_CODE) ON DELETE SET NULL,
    JOB_CODE VARCHAR2(20) REFERENCES T_JOB(JOB_CODE) ON DELETE SET NULL
);

-- 회원별 모든 기존 이력서에 복사한다. 직무가 있으면 직무의 소속 직군을 사용한다.
MERGE INTO T_RESUME R
USING (
    SELECT B.USER_NUM, B.JOB_CODE,
           COALESCE(J.OCCUPATION_CODE, B.OCCUPATION_CODE) AS OCCUPATION_CODE
    FROM T_USER_JOB_CODE_BACKUP B
    LEFT JOIN T_JOB J ON J.JOB_CODE = B.JOB_CODE
) B
ON (R.USER_NUM = B.USER_NUM)
WHEN MATCHED THEN UPDATE SET
    R.OCCUPATION_CODE = B.OCCUPATION_CODE,
    R.JOB_CODE = B.JOB_CODE;

-- 기존 코드가 없는 이력서는 NULL로 유지한다. 다음 작성/수정 시 선택을 받는다.
DECLARE
    MISMATCH_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO MISMATCH_COUNT
    FROM T_RESUME R
    JOIN T_USER_JOB_CODE_BACKUP B ON B.USER_NUM = R.USER_NUM
    LEFT JOIN T_JOB J ON J.JOB_CODE = B.JOB_CODE
    WHERE DECODE(R.JOB_CODE, B.JOB_CODE, 0, 1) = 1
       OR DECODE(R.OCCUPATION_CODE, COALESCE(J.OCCUPATION_CODE, B.OCCUPATION_CODE), 0, 1) = 1;
    IF MISMATCH_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Resume job code migration verification failed');
    END IF;
END;
/
COMMIT;

-- 회원 기본 직군·직무와 이력서별 지원 분야를 각각 관리하므로 T_USER 컬럼도 유지한다.

-- 이력서 없는 회원의 코드도 T_USER와 백업 테이블에 유지한다. 백업은 자동 삭제하지 않는다.
SELECT B.USER_NUM, B.OCCUPATION_CODE, B.JOB_CODE
FROM T_USER_JOB_CODE_BACKUP B
WHERE (B.JOB_CODE IS NOT NULL OR B.OCCUPATION_CODE IS NOT NULL)
  AND NOT EXISTS (SELECT 1 FROM T_RESUME R WHERE R.USER_NUM = B.USER_NUM);
