-- Oracle 19c: 과거 이관으로 삭제한 T_USER 코드 컬럼을 복구할 때 실행한다.
-- 두 컬럼이 이미 있는 DB에서는 변경하지 않는다. 기존 회원/이력서 데이터는 수정하지 않는다.
-- SQL*Plus / SQLcl에서 실행하고 애플리케이션을 배포한다.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_USER' AND COLUMN_NAME = 'OCCUPATION_CODE';
    IF COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_USER ADD (
            OCCUPATION_CODE VARCHAR2(20) REFERENCES T_OCCUPATION(OCCUPATION_CODE) ON DELETE SET NULL)';
    END IF;

    SELECT COUNT(*) INTO COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_USER' AND COLUMN_NAME = 'JOB_CODE';
    IF COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_USER ADD (
            JOB_CODE VARCHAR2(20) REFERENCES T_JOB(JOB_CODE) ON DELETE SET NULL)';
    END IF;
END;
/
