-- ================================================================================
-- Provit (프로빗) 전체 통합 데이터베이스 DDL 스키마 (Oracle 19c)
-- [간결형] 전통적 시퀀스 생성, 컬럼 인라인 PRIMARY KEY / REFERENCES, 필수 UNIQUE만 적용
-- ================================================================================

-- ================================================================================
-- 0. 시퀀스(Sequence) 생성
-- ================================================================================
CREATE SEQUENCE SEQ_T_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_RESUME START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_EDUCATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_CAREER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_CERTIFICATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_COVER_LETTER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_PORTFOLIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_DOCUMENT_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_DOCUMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_STRENGTH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_IMPROVEMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REVIEW_CONSISTENCY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_INTERVIEW_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_RECRUITMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_POST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_STUDY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_T_REPORT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ================================================================================
-- 1. 회원 및 직무 도메인
-- ================================================================================

-- 1-1. 대분류 직군 테이블
CREATE TABLE T_OCCUPATION (
    OCCUPATION_CODE      VARCHAR2(20)        PRIMARY KEY,
    OCCUPATION_NAME      VARCHAR2(200)       NOT NULL
);

-- 1-2. 소분류 직무 테이블
CREATE TABLE T_JOB (
    JOB_CODE             VARCHAR2(20)        PRIMARY KEY,
    OCCUPATION_CODE      VARCHAR2(20)        NOT NULL REFERENCES T_OCCUPATION(OCCUPATION_CODE) ON DELETE CASCADE,
    JOB_NAME             VARCHAR2(200)       NOT NULL
);

-- 1-3. 회원 기본 정보 테이블
CREATE TABLE T_USER (
    USER_NUM             NUMBER(9)           DEFAULT SEQ_T_USER.NEXTVAL PRIMARY KEY,
    USER_NAME            VARCHAR2(100)       NOT NULL,
    USER_NICKNAME        VARCHAR2(100)       NOT NULL,
    USER_BIRTH_DATE      DATE,
    USER_EMAIL           VARCHAR2(200)       NOT NULL UNIQUE,
    USER_PW              VARCHAR2(255)       NOT NULL,
    USER_REGISTER_DATE   DATE                DEFAULT SYSDATE NOT NULL,
    USER_TYPE            VARCHAR2(30)        DEFAULT 'USER',
    USER_IS_DELETED      NUMBER(1)           DEFAULT 0 NOT NULL,
    USER_TOKEN_VERSION   NUMBER(9)           DEFAULT 0 NOT NULL,
    BLOCKED_DATE         TIMESTAMP,
    MAIN_RESUME_NUM      NUMBER(18),
    OCCUPATION_CODE      VARCHAR2(20)        REFERENCES T_OCCUPATION(OCCUPATION_CODE) ON DELETE SET NULL,
    JOB_CODE             VARCHAR2(20)        REFERENCES T_JOB(JOB_CODE) ON DELETE SET NULL
);

-- 탈퇴 회원의 닉네임은 재사용할 수 있고, 활성 회원끼리만 중복을 막는다.
CREATE UNIQUE INDEX UQ_T_USER_ACTIVE_NICKNAME
ON T_USER (CASE WHEN USER_IS_DELETED = 0 THEN USER_NICKNAME END);

-- 로그인 세션별 Refresh Token 식별자 보관. JWT 원문은 저장하지 않는다.
CREATE TABLE T_REFRESH_TOKEN (
    TOKEN_ID             VARCHAR2(36)        PRIMARY KEY,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    EXPIRES_AT           TIMESTAMP           NOT NULL
);

CREATE INDEX IDX_REFRESH_TOKEN_EXPIRES_AT ON T_REFRESH_TOKEN(EXPIRES_AT);


-- ================================================================================
-- 2. 유저 이력 문서 도메인 (이력서 / 자소서 / 포트폴리오)
-- ================================================================================

-- 2-1. 이력서 기본 정보 (1:N 부모)
CREATE TABLE T_RESUME (
    RESUME_NUM           NUMBER(18)          DEFAULT SEQ_T_RESUME.NEXTVAL PRIMARY KEY,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    RESUME_TITLE         VARCHAR2(200),
    OCCUPATION_CODE      VARCHAR2(20)        REFERENCES T_OCCUPATION(OCCUPATION_CODE) ON DELETE SET NULL,
    JOB_CODE             VARCHAR2(20)        REFERENCES T_JOB(JOB_CODE) ON DELETE SET NULL,
    HIGHEST_LEVEL        VARCHAR2(20)        NOT NULL,
    MOTIVATION           CLOB,
    DESIRED_LOCATION     VARCHAR2(200),
    DESIRED_WORK_TYPE    VARCHAR2(100),
    CREATED_AT           DATE                DEFAULT SYSDATE NOT NULL,
    UPDATED_AT           DATE                DEFAULT SYSDATE NOT NULL
);
CREATE INDEX IDX_RESUME_USER_NUM ON T_RESUME(USER_NUM);

-- T_RESUME 생성 후 대표이력서 참조를 추가한다. 삭제된 대표이력서는 미지정 상태로 전환한다.
ALTER TABLE T_USER ADD CONSTRAINT FK_USER_MAIN_RESUME
    FOREIGN KEY (MAIN_RESUME_NUM) REFERENCES T_RESUME(RESUME_NUM) ON DELETE SET NULL;
CREATE INDEX IDX_USER_MAIN_RESUME_NUM ON T_USER(MAIN_RESUME_NUM);

-- 2-2. 학력 정보 (1:N 자식)
CREATE TABLE T_EDUCATION (
    EDU_NUM              NUMBER(18)          DEFAULT SEQ_T_EDUCATION.NEXTVAL PRIMARY KEY,
    RESUME_NUM           NUMBER(18)          NOT NULL REFERENCES T_RESUME(RESUME_NUM) ON DELETE CASCADE,
    SCHOOL_NAME          VARCHAR2(200)       NOT NULL,
    ADMISSION_DATE       DATE,
    GRADUATION_DATE      DATE,
    MAJOR                VARCHAR2(200),
    EDUCATION_STATUS     VARCHAR2(20)        NOT NULL
);
CREATE INDEX IDX_EDU_RESUME_NUM ON T_EDUCATION(RESUME_NUM);
CREATE INDEX IDX_EDU_GRADUATION_DATE ON T_EDUCATION(GRADUATION_DATE);

-- 2-3. 경력 정보 (1:N 자식)
CREATE TABLE T_CAREER (
    CAREER_NUM           NUMBER(18)          DEFAULT SEQ_T_CAREER.NEXTVAL PRIMARY KEY,
    RESUME_NUM           NUMBER(18)          NOT NULL REFERENCES T_RESUME(RESUME_NUM) ON DELETE CASCADE,
    COMPANY_NAME         VARCHAR2(200)       NOT NULL,
    JOIN_DATE            DATE,
    RESIGN_DATE          DATE,
    MAIN_DUTY            VARCHAR2(2000)
);
CREATE INDEX IDX_CAREER_RESUME_NUM ON T_CAREER(RESUME_NUM);
CREATE INDEX IDX_CAREER_RESIGN_DATE ON T_CAREER(RESIGN_DATE);

-- 2-4. 자격증 정보 (1:N 자식)
CREATE TABLE T_CERTIFICATION (
    CERT_NUM             NUMBER(18)          DEFAULT SEQ_T_CERTIFICATION.NEXTVAL PRIMARY KEY,
    RESUME_NUM           NUMBER(18)          NOT NULL REFERENCES T_RESUME(RESUME_NUM) ON DELETE CASCADE,
    CERT_NAME            VARCHAR2(200)       NOT NULL,
    CERT_GRADE           VARCHAR2(100),
    ISSUE_DATE           DATE
);
CREATE INDEX IDX_CERT_RESUME_NUM ON T_CERTIFICATION(RESUME_NUM);
CREATE INDEX IDX_CERT_ISSUE_DATE ON T_CERTIFICATION(ISSUE_DATE);

-- 2-5. 자기소개서 (1:N 관계)
CREATE TABLE T_COVER_LETTER (
    LETTER_NUM                        NUMBER(18)      DEFAULT SEQ_T_COVER_LETTER.NEXTVAL PRIMARY KEY,
    USER_NUM                          NUMBER(9)       NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    COVER_LETTER_TITLE                VARCHAR2(200)   NOT NULL,
    GROWTH_PROCESS                    VARCHAR2(3000),
    PERSONALITY_STRENGTHS_WEAKNESSES  VARCHAR2(3000),
    PROBLEM_SOLVING_EXPERIENCE        VARCHAR2(3000),
    POST_JOINING_ASPIRATION           VARCHAR2(3000),
    CREATED_AT                        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_AT                        DATE            DEFAULT SYSDATE NOT NULL
);
CREATE INDEX IDX_COVER_LETTER_USER_NUM ON T_COVER_LETTER(USER_NUM);

-- 2-6. 포트폴리오 (1:N 관계)
CREATE TABLE T_PORTFOLIO (
    PORTFOLIO_NUM        NUMBER(18)          DEFAULT SEQ_T_PORTFOLIO.NEXTVAL PRIMARY KEY,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    PORTFOLIO_TITLE      VARCHAR2(200)       NOT NULL,
    FILE_URL             VARCHAR2(500),
    ORIGINAL_FILE_NAME   VARCHAR2(255 CHAR),
    SAVED_FILE_NAME      VARCHAR2(255 CHAR),
    CREATED_AT           DATE                DEFAULT SYSDATE NOT NULL,
    UPDATED_AT           DATE                DEFAULT SYSDATE NOT NULL
);
CREATE INDEX IDX_PORTFOLIO_USER_NUM ON T_PORTFOLIO(USER_NUM);


-- ================================================================================
-- 3. AI 원클릭 첨삭 도메인
-- ================================================================================

-- 3-1. 통합 첨삭 요청 및 종합 피드백
CREATE TABLE T_DOCUMENT_REVIEW (
    REVIEW_NUM          NUMBER(18)          DEFAULT SEQ_T_DOCUMENT_REVIEW.NEXTVAL PRIMARY KEY,
    USER_NUM            NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    REQUEST_ID          VARCHAR2(36 CHAR),
    REQUEST_HASH        VARCHAR2(64 CHAR),
    REVIEW_TITLE        VARCHAR2(200 CHAR)  NOT NULL,
    REVIEW_STATUS       VARCHAR2(20 CHAR)   DEFAULT 'PROCESSING' NOT NULL,
    REVIEW_MODE         VARCHAR2(20 CHAR)   DEFAULT 'comprehensive' NOT NULL,
    CUSTOM_CRITERIA     VARCHAR2(200 CHAR),
    INSTRUCTIONS        VARCHAR2(200 CHAR),
    OVERALL_SUMMARY     CLOB,
    CAREER_PREPARATION_JSON CLOB,
    MODEL_NAME          VARCHAR2(100 CHAR),
    PROMPT_VERSION      VARCHAR2(50 CHAR),
    RESPONSE_VERSION    NUMBER(4)           DEFAULT 1 NOT NULL,
    ERROR_MESSAGE       VARCHAR2(1000 CHAR),
    CREATED_AT          TIMESTAMP(6)        DEFAULT LOCALTIMESTAMP NOT NULL,
    FINISHED_AT         TIMESTAMP(6),
    CONSTRAINT CK_REVIEW_MODE CHECK (
        REVIEW_MODE IN ('comprehensive', 'expression', 'consistency', 'jobFit', 'evidence', 'custom')
    ),
    CONSTRAINT CK_REVIEW_CUSTOM CHECK (
        (REVIEW_MODE = 'custom' AND CUSTOM_CRITERIA IS NOT NULL
            AND REGEXP_LIKE(CUSTOM_CRITERIA, '[^[:space:]]'))
        OR (REVIEW_MODE <> 'custom' AND CUSTOM_CRITERIA IS NULL)
    ),
    CONSTRAINT CK_REVIEW_VERSION CHECK (RESPONSE_VERSION > 0),
    CONSTRAINT CK_REVIEW_REQUEST CHECK (
        (REQUEST_ID IS NULL AND REQUEST_HASH IS NULL)
        OR (REQUEST_ID IS NOT NULL AND REQUEST_HASH IS NOT NULL)
    ),
    CONSTRAINT CK_REVIEW_PREPARATION_JSON CHECK (CAREER_PREPARATION_JSON IS JSON STRICT),
    CONSTRAINT CK_REVIEW_STATE CHECK (
        (REVIEW_STATUS = 'PROCESSING' AND FINISHED_AT IS NULL AND ERROR_MESSAGE IS NULL)
        OR (REVIEW_STATUS = 'COMPLETED' AND FINISHED_AT IS NOT NULL AND ERROR_MESSAGE IS NULL)
        OR (REVIEW_STATUS = 'FAILED' AND FINISHED_AT IS NOT NULL AND ERROR_MESSAGE IS NOT NULL)
    ),
    CONSTRAINT CK_REVIEW_TIME CHECK (FINISHED_AT >= CREATED_AT)
);
CREATE INDEX IDX_REVIEW_USER_DATE ON T_DOCUMENT_REVIEW(USER_NUM, CREATED_AT DESC, REVIEW_NUM DESC);
CREATE UNIQUE INDEX UQ_REVIEW_USER_REQUEST ON T_DOCUMENT_REVIEW(
    CASE WHEN REQUEST_ID IS NOT NULL THEN USER_NUM END, REQUEST_ID
);

-- 3-2. 첨삭 당시 문서 스냅샷 및 개별 요약
CREATE TABLE T_REVIEW_DOCUMENT (
    REVIEW_DOCUMENT_NUM NUMBER(18)          DEFAULT SEQ_T_REVIEW_DOCUMENT.NEXTVAL PRIMARY KEY,
    REVIEW_NUM          NUMBER(18)          NOT NULL REFERENCES T_DOCUMENT_REVIEW(REVIEW_NUM) ON DELETE CASCADE,
    DOCUMENT_TYPE       VARCHAR2(20 CHAR)   NOT NULL,
    SOURCE_DOCUMENT_NUM NUMBER(18)          NOT NULL,
    DOCUMENT_TITLE      VARCHAR2(200 CHAR)  NOT NULL,
    SOURCE_UPDATED_AT   DATE,
    SOURCE_SNAPSHOT_JSON CLOB               NOT NULL,
    ORIGINAL_FILE_NAME  VARCHAR2(255 CHAR),
    PDF_SNAPSHOT        BLOB,
    DOCUMENT_SUMMARY    CLOB,
    CONSTRAINT UQ_REVIEW_DOC_TYPE UNIQUE (REVIEW_NUM, DOCUMENT_TYPE),
    CONSTRAINT UQ_REVIEW_DOC_PAIR UNIQUE (REVIEW_NUM, REVIEW_DOCUMENT_NUM),
    CONSTRAINT CK_REVIEW_DOC_TYPE CHECK (
        DOCUMENT_TYPE IN ('resume', 'cover-letter', 'portfolio')
    ),
    CONSTRAINT CK_REVIEW_DOC_SOURCE CHECK (SOURCE_DOCUMENT_NUM > 0),
    CONSTRAINT CK_REVIEW_DOC_JSON CHECK (SOURCE_SNAPSHOT_JSON IS JSON STRICT)
);

-- 3-3. 서류 전체 및 문서별 강점
CREATE TABLE T_REVIEW_STRENGTH (
    STRENGTH_NUM        NUMBER(18)          DEFAULT SEQ_T_REVIEW_STRENGTH.NEXTVAL PRIMARY KEY,
    REVIEW_NUM          NUMBER(18)          NOT NULL REFERENCES T_DOCUMENT_REVIEW(REVIEW_NUM) ON DELETE CASCADE,
    REVIEW_DOCUMENT_NUM NUMBER(18),
    DISPLAY_ORDER       NUMBER(9)           NOT NULL,
    STRENGTH_CONTENT    CLOB                NOT NULL,
    STRENGTH_REASON     CLOB,
    STRENGTH_SUGGESTION CLOB,
    STRENGTH_SOURCES_JSON CLOB,
    CONSTRAINT CK_REVIEW_STR_SOURCES_JSON CHECK (STRENGTH_SOURCES_JSON IS JSON STRICT),
    CONSTRAINT FK_REVIEW_STR_DOC FOREIGN KEY (REVIEW_NUM, REVIEW_DOCUMENT_NUM)
        REFERENCES T_REVIEW_DOCUMENT(REVIEW_NUM, REVIEW_DOCUMENT_NUM) ON DELETE CASCADE,
    CONSTRAINT CK_REVIEW_STR_ORDER CHECK (DISPLAY_ORDER > 0)
);
CREATE UNIQUE INDEX UQ_REVIEW_STR_ORDER ON T_REVIEW_STRENGTH(REVIEW_NUM, NVL(REVIEW_DOCUMENT_NUM, 0), DISPLAY_ORDER);
CREATE INDEX IDX_REVIEW_STR_DOC ON T_REVIEW_STRENGTH(REVIEW_NUM, REVIEW_DOCUMENT_NUM);

-- 3-4. 문서별 개선 제안
CREATE TABLE T_REVIEW_IMPROVEMENT (
    IMPROVEMENT_NUM     NUMBER(18)          DEFAULT SEQ_T_REVIEW_IMPROVEMENT.NEXTVAL PRIMARY KEY,
    REVIEW_DOCUMENT_NUM NUMBER(18)          NOT NULL REFERENCES T_REVIEW_DOCUMENT(REVIEW_DOCUMENT_NUM) ON DELETE CASCADE,
    DISPLAY_ORDER       NUMBER(9)           NOT NULL,
    SECTION_NAME        VARCHAR2(500 CHAR)  NOT NULL,
    IMPROVEMENT_TITLE   VARCHAR2(500 CHAR)  NOT NULL,
    ISSUE_CONTENT       CLOB                NOT NULL,
    ORIGINAL_CONTENT    CLOB                NOT NULL,
    SUGGESTED_CONTENT   CLOB                NOT NULL,
    REASON_CONTENT      CLOB                NOT NULL,
    CONSTRAINT UQ_REVIEW_IMP_ORDER UNIQUE (REVIEW_DOCUMENT_NUM, DISPLAY_ORDER),
    CONSTRAINT CK_REVIEW_IMP_ORDER CHECK (DISPLAY_ORDER > 0)
);

-- 3-5. 서류 간 일관성 검토
CREATE TABLE T_REVIEW_CONSISTENCY (
    CONSISTENCY_NUM     NUMBER(18)          DEFAULT SEQ_T_REVIEW_CONSISTENCY.NEXTVAL PRIMARY KEY,
    REVIEW_NUM          NUMBER(18)          NOT NULL REFERENCES T_DOCUMENT_REVIEW(REVIEW_NUM) ON DELETE CASCADE,
    DISPLAY_ORDER       NUMBER(9)           NOT NULL,
    ISSUE_TYPE          VARCHAR2(30 CHAR)   NOT NULL,
    ISSUE_TITLE         VARCHAR2(500 CHAR)  NOT NULL,
    RECOMMENDATION      CLOB                NOT NULL,
    CONSTRAINT UQ_REVIEW_CON_PAIR UNIQUE (REVIEW_NUM, CONSISTENCY_NUM),
    CONSTRAINT UQ_REVIEW_CON_ORDER UNIQUE (REVIEW_NUM, DISPLAY_ORDER),
    CONSTRAINT CK_REVIEW_CON_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_REVIEW_CON_TYPE CHECK (
        ISSUE_TYPE IN ('mismatch', 'missingEvidence', 'needsConfirmation')
    )
);

-- 3-6. 일관성 항목별 비교 근거 원문
CREATE TABLE T_REVIEW_SOURCE (
    CONSISTENCY_NUM     NUMBER(18)          NOT NULL,
    DISPLAY_ORDER       NUMBER(9)           NOT NULL,
    REVIEW_NUM          NUMBER(18)          NOT NULL,
    REVIEW_DOCUMENT_NUM NUMBER(18)          NOT NULL,
    SECTION_NAME        VARCHAR2(500 CHAR)  NOT NULL,
    SOURCE_CONTENT      CLOB                NOT NULL,
    PAGE_NUMBER         NUMBER(6),
    CONSTRAINT PK_REVIEW_SOURCE PRIMARY KEY (CONSISTENCY_NUM, DISPLAY_ORDER),
    CONSTRAINT FK_REVIEW_SRC_ISSUE FOREIGN KEY (REVIEW_NUM, CONSISTENCY_NUM)
        REFERENCES T_REVIEW_CONSISTENCY(REVIEW_NUM, CONSISTENCY_NUM) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_SRC_DOC FOREIGN KEY (REVIEW_NUM, REVIEW_DOCUMENT_NUM)
        REFERENCES T_REVIEW_DOCUMENT(REVIEW_NUM, REVIEW_DOCUMENT_NUM) ON DELETE CASCADE,
    CONSTRAINT CK_REVIEW_SRC_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_REVIEW_SRC_PAGE CHECK (PAGE_NUMBER > 0)
);
CREATE INDEX IDX_REVIEW_SRC_ISSUE ON T_REVIEW_SOURCE(REVIEW_NUM, CONSISTENCY_NUM);
CREATE INDEX IDX_REVIEW_SRC_DOC ON T_REVIEW_SOURCE(REVIEW_NUM, REVIEW_DOCUMENT_NUM);

-- 첨삭 테이블 한글 주석
COMMENT ON TABLE T_DOCUMENT_REVIEW IS '사용자별 통합 첨삭 요청과 종합 결과';
COMMENT ON TABLE T_REVIEW_DOCUMENT IS '첨삭 당시 문서 스냅샷과 문서별 종합 피드백';
COMMENT ON TABLE T_REVIEW_STRENGTH IS '서류 전체 및 문서별 강점';
COMMENT ON TABLE T_REVIEW_IMPROVEMENT IS '문서별 원문과 수정 제안 및 이유';
COMMENT ON TABLE T_REVIEW_CONSISTENCY IS '서류 간 일관성 검토 항목';
COMMENT ON TABLE T_REVIEW_SOURCE IS '일관성 검토 항목별 비교 근거';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.REVIEW_MODE IS '전체 종합 또는 중심 첨삭 기준 1개; comprehensive, expression, consistency, jobFit, evidence, custom';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.CUSTOM_CRITERIA IS '직접 입력 기준; custom일 때 필수이며 최대 200자, 다른 기준에서는 NULL';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.INSTRUCTIONS IS '선택 입력인 추가 요청; 최대 200자';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.MODEL_NAME IS '생성 모델; gpt-6.1-sol, 기존 gpt-6-sol 또는 더미 기록의 dummy-document-review-v2';
COMMENT ON COLUMN T_DOCUMENT_REVIEW.CAREER_PREPARATION_JSON IS '당시 이력서의 지원 직군·직무와 별도 취업 준비 추천 결과 JSON';
COMMENT ON COLUMN T_REVIEW_DOCUMENT.SOURCE_DOCUMENT_NUM IS '원본 문서 번호의 기록용 복사본; 원본 삭제와 독립적으로 보존';
COMMENT ON COLUMN T_REVIEW_DOCUMENT.SOURCE_SNAPSHOT_JSON IS '요청 당시 선택한 실제 문서 내용과 메타데이터 보관본';
COMMENT ON COLUMN T_REVIEW_DOCUMENT.PDF_SNAPSHOT IS '포트폴리오 원본 PDF를 다시 제공할 경우 사용하는 보관본';
COMMENT ON COLUMN T_REVIEW_STRENGTH.REVIEW_DOCUMENT_NUM IS 'NULL이면 서류 전체 강점, 값이 있으면 해당 문서의 강점';


-- ================================================================================
-- 4. AI 모의 면접 도메인
-- ================================================================================

-- 4-1. 면접 Q&A 내역 (순수 질문/답변 기록)
CREATE TABLE T_INTERVIEW_HISTORY (
    HISTORY_NUM          NUMBER(18)          DEFAULT SEQ_T_INTERVIEW_HISTORY.NEXTVAL PRIMARY KEY,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    QUESTION1            VARCHAR2(120 CHAR),
    ANSWER1              VARCHAR2(1000 CHAR),
    QUESTION2            VARCHAR2(120 CHAR),
    ANSWER2              VARCHAR2(1000 CHAR),
    QUESTION3            VARCHAR2(120 CHAR),
    ANSWER3              VARCHAR2(1000 CHAR),
    QUESTION4            VARCHAR2(120 CHAR),
    ANSWER4              VARCHAR2(1000 CHAR),
    QUESTION5            VARCHAR2(120 CHAR),
    ANSWER5              VARCHAR2(1000 CHAR),
    INTERVIEW_DATE       DATE                DEFAULT SYSDATE NOT NULL
);
CREATE INDEX IDX_INTERVIEW_USER_NUM ON T_INTERVIEW_HISTORY(USER_NUM);

-- 4-2. 면접 평가 결과 (점수 및 LLM 역량 피드백, 복합 기본키)
CREATE TABLE T_INTERVIEW_RESULT (
    HISTORY_NUM          NUMBER(18)          NOT NULL REFERENCES T_INTERVIEW_HISTORY(HISTORY_NUM) ON DELETE CASCADE,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    DOCUMENT_CONSISTENCY_SCORE NUMBER(5,2)     DEFAULT 0.00,
    EXPERTISE_SCORE      NUMBER(5,2)         DEFAULT 0.00,
    PROBLEM_SOLVING_SCORE NUMBER(5,2)        DEFAULT 0.00,
    LOGIC_SCORE          NUMBER(5,2)         DEFAULT 0.00,
    COMMUNICATION_SCORE NUMBER(5,2)         DEFAULT 0.00,
    TOTAL_SCORE          NUMBER(5,2)         DEFAULT 0.00,
    STRENGTH             VARCHAR2(250 CHAR),
    WEAKNESS             VARCHAR2(250 CHAR),
    PREVIOUS_COMPARISON  VARCHAR2(250 CHAR),
    IMPROVEMENT_POINT    VARCHAR2(250 CHAR),
    INTERVIEW_DATE       DATE                DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (HISTORY_NUM, USER_NUM)
);


-- ================================================================================
-- 5. 채용 공고 도메인
-- ================================================================================

-- 5-1. 사람인 채용 공고 API 적재 테이블
CREATE TABLE T_RECRUITMENT (
    RECRUITMENT_NUM      NUMBER(18)          DEFAULT SEQ_T_RECRUITMENT.NEXTVAL PRIMARY KEY,
    SARAMIN_JOB_ID       VARCHAR2(50)        NOT NULL UNIQUE,
    COMPANY_NAME         VARCHAR2(200)       NOT NULL,
    TITLE                VARCHAR2(400)       NOT NULL,
    JOB_URL              VARCHAR2(500)       NOT NULL,
    LOCATION_NAME        VARCHAR2(200),
    JOB_NAME             VARCHAR2(300),
    EXPERIENCE_LEVEL     VARCHAR2(100),
    EXPIRATION_DATE      DATE,
    CLOSE_TYPE           VARCHAR2(50),
    IS_ACTIVE            NUMBER(1)           DEFAULT 1 NOT NULL,
    CREATED_AT           DATE                DEFAULT SYSDATE NOT NULL
);
CREATE INDEX IDX_RECRUIT_ACTIVE_EXP ON T_RECRUITMENT(IS_ACTIVE, EXPIRATION_DATE);

-- 5-2. 관심 채용 공고 스크랩 (N:M 해소, 복합 기본키)
CREATE TABLE T_JOB_SCRAP (
    RECRUITMENT_NUM      NUMBER(18)          NOT NULL REFERENCES T_RECRUITMENT(RECRUITMENT_NUM) ON DELETE CASCADE,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    CREATED_AT           DATE                DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (RECRUITMENT_NUM, USER_NUM)
);
CREATE INDEX IDX_SCRAP_USER ON T_JOB_SCRAP(USER_NUM);


-- ================================================================================
-- 6. 커뮤니티 및 스터디 도메인
-- ================================================================================

-- 6-1. 게시판 카테고리 종류
CREATE TABLE T_CATEGORY (
    CATEGORY_NUM         NUMBER(9)           DEFAULT SEQ_T_CATEGORY.NEXTVAL PRIMARY KEY,
    CATEGORY_NAME        VARCHAR2(100)       NOT NULL
);

-- 6-2. 커뮤니티 게시글
CREATE TABLE T_POST (
    POST_NUM             NUMBER(18)          DEFAULT SEQ_T_POST.NEXTVAL PRIMARY KEY,
    CATEGORY_NUM         NUMBER(9)           NOT NULL REFERENCES T_CATEGORY(CATEGORY_NUM) ON DELETE CASCADE,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    POST_TITLE           VARCHAR2(300)       NOT NULL,
    POST_CONTENT         VARCHAR2(4000),
    POST_LIKE_COUNT      NUMBER(9)           DEFAULT 0 NOT NULL,
    VIEW_COUNT           NUMBER(9)           DEFAULT 0 NOT NULL,
    POST_FILE            VARCHAR2(500),
    POST_DATE            DATE                DEFAULT SYSDATE NOT NULL
);
CREATE INDEX IDX_POST_CATEGORY ON T_POST(CATEGORY_NUM);
CREATE INDEX IDX_POST_USER ON T_POST(USER_NUM);

-- 6-3. 게시글 좋아요 (N:M 해소, 복합 기본키)
CREATE TABLE T_POST_LIKE (
    POST_NUM             NUMBER(18)          NOT NULL REFERENCES T_POST(POST_NUM) ON DELETE CASCADE,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    CREATED_AT           DATE                DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (POST_NUM, USER_NUM)
);

-- 6-4. 게시글 댓글
CREATE TABLE T_COMMENT (
    COMMENT_NUM          NUMBER(18)          DEFAULT SEQ_T_COMMENT.NEXTVAL PRIMARY KEY,
    POST_NUM             NUMBER(18)          NOT NULL REFERENCES T_POST(POST_NUM) ON DELETE CASCADE,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    COMMENT_CONTENT      VARCHAR2(2000)      NOT NULL,
    COMMENT_DATE         DATE                DEFAULT SYSDATE NOT NULL,
    PARENT_COMMENT_NUM   NUMBER(18)          REFERENCES T_COMMENT(COMMENT_NUM),
    IS_DELETED           NUMBER(1)           DEFAULT 0 NOT NULL
);
CREATE INDEX IDX_COMMENT_POST ON T_COMMENT(POST_NUM);
CREATE INDEX IDX_COMMENT_USER ON T_COMMENT(USER_NUM);

-- 6-5. 스터디 모집 방
CREATE TABLE T_STUDY (
    STUDY_NUM            NUMBER(18)          DEFAULT SEQ_T_STUDY.NEXTVAL PRIMARY KEY,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    STUDY_NAME           VARCHAR2(200)       NOT NULL,
    STUDY_EXPLAIN        VARCHAR2(2000),
    MAX_MEMBERS          NUMBER(4)           DEFAULT 10 NOT NULL CHECK (MAX_MEMBERS >= 2),
    STUDY_CREATE_DATE    DATE                DEFAULT SYSDATE NOT NULL
);

-- 6-6. 스터디 참여자 명단 (복합 기본키)
CREATE TABLE T_STUDY_MEMBER (
    STUDY_NUM            NUMBER(18)          NOT NULL REFERENCES T_STUDY(STUDY_NUM) ON DELETE CASCADE,
    USER_NUM             NUMBER(9)           NOT NULL REFERENCES T_USER(USER_NUM) ON DELETE CASCADE,
    STUDY_JOIN_DATE      DATE                DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (STUDY_NUM, USER_NUM)
);

-- 6-7. 신고 내역 관리 (T_REPORT)
CREATE TABLE T_REPORT (
    REPORT_NUM           NUMBER(18)          DEFAULT SEQ_T_REPORT.NEXTVAL PRIMARY KEY,
    REPORTER_NUM         NUMBER(9)           REFERENCES T_USER(USER_NUM) ON DELETE SET NULL,
    TARGET_TYPE          VARCHAR2(20)        NOT NULL, -- 'POST' or 'COMMENT'
    TARGET_NUM           NUMBER(18)          NOT NULL,
    REPORT_REASON        VARCHAR2(100)       NOT NULL,
    REPORT_STATUS        VARCHAR2(20)        DEFAULT 'PENDING' NOT NULL,
    REPORT_DATE          DATE                DEFAULT SYSDATE NOT NULL
);

CREATE INDEX IDX_REPORT_STATUS ON T_REPORT(REPORT_STATUS);
CREATE INDEX IDX_REPORT_TARGET ON T_REPORT(TARGET_TYPE, TARGET_NUM);

-- ==========================================
-- 7. 기초 데이터 (Seed Data) 삽입
-- ==========================================

-- T_CATEGORY 기본 게시판 카테고리 설정 (프론트엔드와 매핑)
INSERT INTO T_CATEGORY (CATEGORY_NUM, CATEGORY_NAME) VALUES (1, '질문');
INSERT INTO T_CATEGORY (CATEGORY_NUM, CATEGORY_NAME) VALUES (2, '정보');
INSERT INTO T_CATEGORY (CATEGORY_NUM, CATEGORY_NAME) VALUES (3, '후기');
COMMIT;

