# Oracle 19c \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC811\uC18D \uC815\uBCF4
db.driverClassName=oracle.jdbc.OracleDriver

# JDBC URL (\uD300 \uACF5\uD1B5 Oracle 19c \uAE30\uBCF8 SID\uB294 orcl \uC785\uB2C8\uB2E4)
# SID \uBC29\uC2DD:
db.url=jdbc:oracle:thin:@localhost:1521:orcl
# (\uD639\uC2DC \uBCF8\uC778 \uB85C\uCEEC \uC624\uB77C\uD074\uC774 \uC11C\uBE44\uC2A4\uBA85 \uBC29\uC2DD\uC774\uBA74: jdbc:oracle:thin:@localhost:1521/orcl)

# \uBCF8\uC778\uC758 \uC624\uB77C\uD074 \uACC4\uC815 \uBC0F \uBE44\uBC00\uBC88\uD638 \uC785\uB825
db.username=scott
db.password=tiger

# \uCEE4\uB125\uC158 \uD480 \uC124\uC815
db.maxPoolSize=10
db.minIdle=2